[package]
name = "ch13-01-closures"
version = "0.1.0"
authors = ["Sijie Shen <sijie.shen@dji.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
