[package]
name = "ch12_minigrep"
version = "0.1.0"
authors = ["Sijie Shen <sijie.shen@dji.com>"]
edition = "2018"

[lib]
name="ch12_minigrep"
path="src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
